name: Cron Fetch and Process

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: {}

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run fetch
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          MONGODB_DB: ${{ secrets.MONGODB_DB || 'newsdb' }}
        run: |
          python scripts/fetch_rss.py
      - name: Run process
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          MONGODB_DB: ${{ secrets.MONGODB_DB || 'newsdb' }}
        run: |
          python scripts/process_article.py
